---
version: "1"
run:
  deadline: 1m
linters:
  # enable-all: true
  enable:
    # - gosec
    - unconvert
    - gocyclo
    - goconst
    - goimports
    - gocritic
    - govet
    - revive
issues:
  exclude-use-default: false
