---
rules:
  unpinned-uses:
    config:
      policies:
        actions/*: ref-pin
        github/*: ref-pin
        super-linter/super-linter: ref-pin
        codecov/codecov-action: ref-pin
        astral-sh/setup-uv: ref-pin
        dtolnay/rust-toolchain: ref-pin
