name: Automation TeX Flashcards

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-18.04
    steps:
      - name: Initiating
        uses: actions/checkout@v2.3.4
      - name: Preparing
        run: |
          sudo apt-get install texlive-full
      - name: Building
        run: |
          cd algorithms
          pdflatex -halt-on-error -interaction=nonstopmode algorithms.tex
          cd -
      - name: Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_SHA:0:7}" --notes "${GITHUB_SHA:0:7}"
          gh release upload "${GITHUB_SHA:0:7}" algorithms/algorithms.pdf
