---
name: Rust

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Initiating
        uses: actions/checkout@v4
      - name: Preparing
        uses: dtolnay/rust-toolchain@1.80.0
      - name: Linting
        run: |
          /bin/sh .github/workflows/rust.linter.sh
      - name: Testing
        run: |
          /bin/sh .github/workflows/rust.tester.sh
      - name: Reporting
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: rust
