---
name: C#

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-20.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Initiating
        uses: actions/checkout@v1
      - name: Preparing
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Linting
        run: |
          /bin/sh .github/workflows/csharp.linter.get.sh
          /bin/sh .github/workflows/csharp.linter.run.sh
      - name: Testing
        run: |
          /bin/sh .github/workflows/csharp.tester.get.sh
          /bin/sh .github/workflows/csharp.tester.run.sh
      - name: Reporting
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: csharp
